export type {
  AlmanacToolInput,
  BaziToolInput,
  CeziToolInput,
  ChenguzToolInput,
  ComboAnnualFortuneToolInput,
  ComboDailyWellnessToolInput,
  ComboDecisionToolInput,
  ComboMarriagePersonToolInput,
  ComboMarriageToolInput,
  ComboMonthlyFortuneToolInput,
  ComboSanshiClassicToolInput,
  ComboSanshiToolInput,
  ComboSpaceTimeToolInput,
  ComboZeriToolInput,
  ConstitutionAnswerToolInput,
  ConstitutionAssessmentToolInput,
  ConstitutionQuestionnaireToolInput,
  ConstitutionTendencyToolInput,
  DailyRhythmToolInput,
  DaliurenToolInput,
  DivinationBirth,
  DreamToolInput,
  HuangjiToolInput,
  LiuyaoToolInput,
  LocalToolContractInput,
  LocalToolInputByName,
  LocalToolName,
  MeihuaToolInput,
  NameToolInput,
  ParsedLocalToolCall,
  QimenToolInput,
  TaiyiToolInput,
  TrueSolarTimeToolInput,
  XiYongToolInput,
  XingxiuToolInput,
  YunqiToolInput,
} from './toolContracts';

export type LocalToolInput<T extends import('./localToolRegistry').LocalToolName> =
  import('./toolContracts').LocalToolInputByName[T];
