export {
  compareBaziShenShaRules,
  compareBaziTimeBasis,
  compareChenguzVersions,
  compareDaliurenSchools,
  compareStructuredVariants,
  compareTaiyiRules,
  compareZiweiDynamicScope,
  parseRuleComparisonRequest,
  runRuleComparison,
} from '@/legacy/ruleComparison';
export type {
  BaziShenShaComparisonInput,
  BaziShenShaRuleComparisonRequest,
  BaziTimeBasisComparisonInput,
  BaziTimeBasisRuleComparisonRequest,
  ChenguzVersionComparisonInput,
  ChenguzVersionRuleComparisonRequest,
  DaliurenSchoolComparisonInput,
  DaliurenSchoolRuleComparisonRequest,
  RuleCitation,
  RuleComparisonDifference,
  RuleComparisonDomain,
  RuleComparisonFact,
  RuleComparisonRequest,
  RuleComparisonResult,
  RuleVariantResult,
  StructuredValue,
  TaiyiRuleComparisonInput,
  TaiyiRuleComparisonRequest,
  TaiyiRuleConfig,
  ZiweiDynamicScopeComparisonInput,
  ZiweiDynamicScopeRuleComparisonRequest,
} from '@/legacy/ruleComparison';
